[package]
name = "open-workshop-storage"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
axum = { version = "0.7", features = ["ws", "multipart"] }
bcrypt = "0.16"
base64 = "0.22"
blurhash = "0.2.3"
anyhow = "1"
futures-util = "0.3"
hmac = "0.12"
image = { version = "0.24.1", default-features = false, features = ["webp"] }
lru = "0.12"
bytes = "1"
http-body-util = "0.1"
hyper = { version = "1", features = ["client", "http1"] }
hyper-util = { version = "0.1", features = ["client-legacy", "http1", "tokio"] }
once_cell = "1"
regex = "1"
rand = "0.8"
redis = { version = "1.2", features = ["aio", "tokio-comp"] }
sha2 = "0.10.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio-util = { version = "0.7", features = ["io"] }
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
serde_urlencoded = "0.7"

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
